#!/bin/bash
# Copyright © 2015 Jan Keromnes. All rights reserved.
# The following code is covered by the AGPL-3.0 license.

JANITOR_DIR="/path/to/janitor"

do_start() {
  cd $JANITOR_DIR && make start
}

do_stop() {
  cd $JANITOR_DIR && make stop
}

do_check() {
  if [ -e $JANITOR_DIR/janitor.pid -a -n "$(ps h $(cat $JANITOR_DIR/janitor.pid 2>/dev/null))" ] ; then echo "OK" ; else echo "FAIL" ; fi
}

case "$1" in
  restart|reload)
    do_stop
    do_start
  ;;
  start)
    do_start
  ;;
  stop)
    do_stop
  ;;
  status)
    do_check
  ;;
  *)
    echo "Script only started at boot for system configuration."
  ;;
esac

exit 0

