name: CI

on:
  push:
  pull_request:

env:
  NODE: 10.x

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "${{ env.NODE }}"

      - name: Install npm dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Run tests
        run: npm test
